typography_spectrum: 0.05967
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4634748916141689
  lightness: 0.42067937715910375
  saturation: 0.7996015292592347
  rhythmicContrast: 0.7426223654765636
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9242434427142143
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/41a35907-730e-4b21-873d-dd31b8b99250.jpg
name: No Direction
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e2385fa6-bf41-4293-a6c9-7517ed3e5660.jpg
title: No Direction
purpose: []
